version: "3.1"

services:
  app:
    # image: morzecrew/morzebot-backend-app:latest
#    restart: on-failure
    command: python3.8 server.py
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./data:/mz_bot/ai/data
    ports:
      - 8000:8000