version: "3.1"

services:
  app:
    image: morzecrew/morzebot-admin:latest
#    restart: on-failure
    command: python3.8 server.py
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./data:/mz_bot/ai/data
    ports:
      - 8000:8000

  mongo:
    command: mongod
    image: mongo:4.0.0
    ports:
      - 27017:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock