name: Deploy-Dev

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USER }}/morzebot-ai-v2:latest
        -
          name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            known_hosts: '-'
        -
          name: Adding Known Hosts
          run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        -
          name: Deploy
          run: ssh root@${{ secrets.SSH_HOST }} "cd ${{secrets.PROJECT_DIR}}; docker login -u ${{ secrets.DOCKER_USER }} docker -p ${{ secrets.DOCKER_ACCESS_TOKEN }}; docker-compose down; docker-compose pull; docker-compose up -d"